[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && echo 'Build completed successfully'"
]

[start]
cmd = ". /opt/venv/bin/activate && python railway_app.py"

# Use custom Dockerfile
[phases.setup]
providers = ["dockerfile"] 