[phases.setup]
nixPkgs = ["python312", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python railway_app.py" 